language: node_js
node_js:
  - "8"
before_install:
  - "npm i -g firebase-tools"
script:
  - "npm run build"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "my-food-diary"
  message: "Deploying to Firebase from Travis CI"
