language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
before_install:
 - gem install rake
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project development-3a1e8 — token $FIREBASE_TOKEN.
